version: '3.7'

services:  
  api:
    restart: always
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
    links: 
      - mongo
    depends_on: 
      - "mongo"
  mongo:
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"