version: '3.7'

services:  
  api:
    restart: always
    container_name: api
    build:
      context: .
      dockerfile: Api.Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "9000:9000"
    environment:
      - WAIT_HOSTS=mongo:27017
      - MONGODB_ADDON_URI=mongodb://mongo:27017/trello
      - NODE_ENV=development
    depends_on: 
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"